# Generated by Django 4.2.5 on 2023-09-29 12:41

import anket.models
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from=anket.models.turkish_charset_convert),
        ),
        migrations.CreateModel(
            name='AnswerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='anket.answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anket.exam')),
                ('questions', models.ManyToManyField(to='anket.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
