# Generated by Django 4.2.5 on 2023-09-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0002_remove_answer_user_alter_exam_slug_answerlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlist',
            name='user',
        ),
        migrations.AddField(
            model_name='answerlist',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
