# Generated by Django 4.2.5 on 2023-09-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0004_remove_answerlist_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerquestionhandle',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='answerquestionhandle',
            name='questions',
        ),
        migrations.AddField(
            model_name='answerquestionhandle',
            name='answer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anket.answer'),
        ),
        migrations.AddField(
            model_name='answerquestionhandle',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anket.question'),
        ),
    ]
