# Generated by Django 4.2.5 on 2023-09-30 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0005_remove_answerquestionhandle_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlist',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
