# Generated by Django 4.2.5 on 2023-10-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0007_alter_answerlist_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlist',
            name='email',
        ),
    ]
