# Generated by Django 4.2.5 on 2023-10-16 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anket', '0008_remove_answerlist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlist',
            name='user',
            field=models.ForeignKey(default='f4rukseker@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
