# Generated by Django 4.2.5 on 2023-11-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pars_auth', '0002_alter_emailconfirmation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirmation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_email_confirmations', to='pars_auth.emailconfirmation'),
        ),
    ]
