# Generated by Django 4.2.5 on 2023-11-23 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pars_auth', '0003_alter_user_email_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('used', models.BooleanField(default=False)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, unique_for_date=True)),
                ('token_type', models.CharField(choices=[('pwr', 'Password Reset Token'), ('lwt', 'Login With Token')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginToken',
        ),
    ]
