# Generated by Django 4.2.5 on 2023-11-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pars_auth', '0005_alter_basetoken_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basetoken',
            old_name='created',
            new_name='last_update',
        ),
    ]
